### ISSUE TITLE
多参数时 Int 等基本类型 KSP 未生成 append

### ISSUE THREAD

**Issue by 985892345** [qdsfdhvh/ktor-fit#8]
## 例子
```kotlin
@POST("/test")
@FormUrlEncoded
suspend fun test(
  @Field("name")
  name: String,
  @Field("num")
  num: Int,
)

// KSP 生成的代码为：
override suspend fun test(name: String, num: Int) {
  val result = client.request {
    method = HttpMethod.parse("POST")
    url("/test")
    val parameters = Parameters.build {
      append("name", name)
    }
    setBody(FormDataContent(parameters))
  }
  return result.body()
}
```
可以发现只生成了 name，num 却没有生成
## 触发问题的源码地址
https://github.com/qdsfdhvh/ktor-fit/blob/bdfb9b0f17795da866a42ef798cc52a3af20aec6/ktor-fit-ksp/src/main/kotlin/io/github/seiko/ktorfit/KtorfitClassVisitor.kt#L350

代码中未判断其是否为基本类型

**Comment by qdsfdhvh** [comment]
你的项目方便升级到 `kotlin 2.0.0-RC2+` 吗，不方便的话，我就基于 1.9.23 发布。

**Comment by 985892345** [comment]
> 你的项目方便升级到 `kotlin 2.0.0-RC2+` 吗，不方便的话，我就基于 1.9.23 发布。

方便的话1.9.23发一个修护版吧

**Comment by qdsfdhvh** [comment]
上传了 `1.9.23-1.1.0`。
